services:
  back:
    build:
      dockerfile: ./meu_app_api/Dockerfile
    ports:
      - "5000:5000"
    restart: always
    container_name: meu_app_api
    networks:
      - meu_app_net

  front:
    build:
      dockerfile: ./meu_app_front/Dockerfile
    ports:
      - "3000:3000"
    links:
      - back
    restart: always
    container_name: meu_app_front
    networks:
      - meu_app_net

networks:
  meu_app_net:
    driver: bridge